/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

export type SetPaymentMethodParams = {
  /**
   * The payment method ID generated by Stripe.js
   */
  paymentMethodId: string;
};
