import type { CSSProperties } from 'react';
// Defines the visual style variant options for the chat widget.
export type Variant = 'default' | 'glassy' | 'minimal';
// Defines the size options for the chat widget.
export type Size = 'sm' | 'md' | 'lg';
// Defines the possible roles for a message sender within the chat.
export type MessageRole = 'user' | 'assistant';
// Defines the structure for an attachment object.
export interface Attachment {
  // A unique identifier for the attachment.
  id: string;
  // The display name of the attachment file.
  name: string;
  // Optional size of the attachment in bytes.
  size?: number;
  // Optional MIME type of the attachment.
  type?: string;
  // Optional URL to access or preview the attachment.
  url?: string;
}
// Defines the structure for an interactive context element.
export interface ContextElement {
  // A unique identifier for the context element.
  id: string;
  // The display name or title of the context element.
  name: string;
  // The HTML tag name of the context element (e.g., 'DIV', 'P').
  tagName: string;
  // Optional bounding rectangle of the context element in the DOM.
  rect?: DOMRect;
}
// Defines the specific types of messages that can be displayed in the chat.
export type MessageType = 'text' | 'error' | 'system' | 'tool';
// Defines the structure for a single chat message.
export interface Message {
  // A unique identifier for the message.
  id: string;
  // The role of the sender of the message (e.g., 'user', 'assistant').
  role: MessageRole;
  // The main textual content of the message.
  content: string;
  // Optional explanation or reasoning behind an assistant's response.
  reasoning?: string;
  // Optional specific type of the message (e.g., 'text', 'error', 'system', 'tool').
  messageType?: MessageType;
  // The date and time when the message was sent or received.
  timestamp: Date;
  // Optional array of attachments associated with the message.
  attachments?: Attachment[];
  // Optional array of context elements referenced in the message.
  contextElements?: ContextElement[];
}
// Defines the available styling points for customizing the chat widget's appearance.
export interface ChatWidgetStyles {
  // Styles for the main container element of the chat widget.
  container?: any;
  // Styles for the container that holds all chat messages.
  messagesContainer?: any;
  // Styles for the container holding the message input area.
  inputContainer?: any;
  // General styles for a chat message bubble.
  bubble?: any;
  // Styles specifically for message bubbles sent by the user.
  userBubble?: any;
  // Styles specifically for message bubbles sent by the assistant.
  assistantBubble?: any;
  // Styles for the timestamp displayed on messages.
  timestamp?: any;
  // Styles for the message input field.
  input?: any;
  // Styles for the button used to send messages.
  sendButton?: any;
  // Styles for the button used to add attachments to a message.
  attachmentButton?: any;
  // Styles for the loading animation or indicator within the chat.
  loadingIndicator?: any;
  // Styles for the container holding context chips or indicators.
  contextChipsContainer?: any;
  // Styles for the button that opens the context selection interface.
  contextPickerButton?: any;
  // Styles for the container displaying the assistant's reasoning.
  reasoningContainer?: any;
  // Styles for the actual content of the assistant's reasoning.
  reasoningContent?: any;
  // Styles for displaying error messages within the chat.
  errorMessage?: any;
  // Styles for displaying system-generated messages.
  systemMessage?: any;
  // Styles for displaying messages generated by tools or functions.
  toolMessage?: any;
}
